#pragma once
#include "ofMain.h"
enum ofxWiiuseButtonEventType{
    OFXWIIUSE_BUTTON_A_PRESSED,
    OFXWIIUSE_BUTTON_B_PRESSED,
    OFXWIIUSE_BUTTON_MINUS_PRESSED,
    OFXWIIUSE_BUTTON_PLUS_PRESSED,
    OFXWIIUSE_BUTTON_UP_PRESSED, 
    OFXWIIUSE_BUTTON_RIGHT_PRESSED,
    OFXWIIUSE_BUTTON_DOWN_PRESSED,
    OFXWIIUSE_BUTTON_LEFT_PRESSED,
    OFXWIIUSE_BUTTON_ONE_PRESSED,
    OFXWIIUSE_BUTTON_TWO_PRESSED,
    OFXWIIUSE_BUTTON_HOME_PRESSED,
    OFXWIIUSE_BUTTON_A_RELEASED,
    OFXWIIUSE_BUTTON_B_RELEASED,
    OFXWIIUSE_BUTTON_MINUS_RELEASED,
    OFXWIIUSE_BUTTON_PLUS_RELEASED,
    OFXWIIUSE_BUTTON_UP_RELEASED, 
    OFXWIIUSE_BUTTON_RIGHT_RELEASED,
    OFXWIIUSE_BUTTON_DOWN_RELEASED,
    OFXWIIUSE_BUTTON_LEFT_RELEASED,
    OFXWIIUSE_BUTTON_ONE_RELEASED,
    OFXWIIUSE_BUTTON_TWO_RELEASED,
    OFXWIIUSE_BUTTON_HOME_RELEASED
};
enum ofxWiiuseControlEventType
{
    OFXWIIUSE_CONNECTED,
    OFXWIIUSE_DISCONNECTED
};

typedef pair<int, ofxWiiuseButtonEventType> ofxWiiuseButtonEventArgs;//(id,type)
typedef pair<int, ofxWiiuseControlEventType> ofxWiiuseControlEventArgs;//(id,type)
typedef pair<int, vector<float> > ofxWiiuseMotionEventArgs;//(id,values)
